branches:
  - label: förbättring
    name: Develop
    prefix: feature/
  - label: Todo
    name: Develop
    prefix: feature/
  - label: bugg
    name: Develop
    prefix: bugfix/
  - label: '*'
    prefix: issues/
branchName: short
