# Add 'repo' label to any root file changes
repo:
  - ./*
  
# Add 'backend' label to any backend changes
backend:
  - backend/*
  
# Add 'frontend' label to any frontend changes
frontend:
  - frontend/*
